import 'package:get_storage/get_storage.dart';

final box = GetStorage();
var shortActionList = [
  "Actrapid",
  "Afrezza",
  "Apidra",
  "Fiasp",
  "Liprolog",
  "Novolin R",
  "NovoRapid",
  "Gensulin R",
  "Humalog",
  "Humulin R",
  "Insuman R",
  "Liprolog ",
  "Novolog",
  "Regular",
  "U-500"
];
var longActionList = [
  "Gensulin N",
  "Humalog Mix75/25",
  "Humlin 70/30",
  "Humulin N",
  "Insulatard ",
  " Insuman N",
  "Lantus ",
  "Levemir",
  "Mixtard 30",
  "Novolin 70/30",
  "Novolog 30/70",
  "Novolog 50/50 ",
  "Novolog 70/30",
  "NovoMix 30",
  "NovoMix 50",
  "NovoMix70",
  "NovoRapid 70/30",
  "NPH",
  "Protaphane",
  "Ryzodeg",
  "Toujeo",
  "Tresiba",
  "Basaglar",
];
